# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code path
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Install Packages
        run: npm install

      - name: Build
        run: |
          npm run build

      - name: Test
        run: npm run test
