# This is a basic workflow to help you get started with Actions

name: release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          cd  ./test-angular
          npm run build
      - name: Test
        run: npm run test
