name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      artifact_name:
        description: 'Name of the artifact to deploy'
        required: false
        default: dist
        type: string
    outputs:
      result:
        description: 'The result of the deployment'
        value: ${{ jobs.output.outputs.result }}
    # secrets:
    #   required: true
jobs:
  output:
    outputs:
      result: ${{ steps.set-result.outputs.result }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: List Files
        run: ls
      - name: Output Information
        run: echo "Deploying to production"
      - name: Set Result Output
        run: echo "::set-output name=result::success"